config/routes.rb
Rails.application.routes.draw do
  resources :imports, only: [ :new, :create, :show ]

  resources :categories
  root "films#index"

  resources :films do
    resources :comments, only: [ :create ]
  end

  devise_for :users

  require "sidekiq/web"
  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

 def create
  file = params[:csv_file]


  extension = (File.extname(file.original_filename) == ".csv") ? ".csv" : ".tmp"

  unique_filename = "#{Time.current.to_i}_#{SecureRandom.hex(4)}_import_data#{extension}"

  path = Rails.root.join("tmp", unique_filename)
  File.open(path, "wb") { |f| f.write(file.read) }
  import_status = current_user.import_statuses.create(status: "pending")
  ImportMoviesJob.perform_async(path.to_s, current_user.id, import_status.id)
  redirect_to import_path(import_status)
end

  def show
    @import_status = ImportStatus.find(params[:id])
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/create.html.erb
<h1>Imports#create</h1>
<p>Find me in app/views/imports/create.html.erb</p>

app/views/imports/new.html.erb
<h1>Importar filmes via CSV</h1>
<%= form_with url: imports_path, local: true, multipart: true do |form| %>
  <%= form.file_field :csv_file %>
  <%= form.submit "Importar Filmes", data: { turbo_submits_with: "Importando..." } %>
<% end %>

app/views/imports/show.html.erb
<h1>Status da Importação</h1>
<p>Status: <%= @import_status.status %></p>