config/routes.rb
Rails.application.routes.draw do
  resources :imports, only: [ :new, :create, :show ]

  resources :categories
  root "films#index"

  resources :films do
    resources :comments, only: [ :create ]
  end

  devise_for :users

  require "sidekiq/web"
  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 2, maximum: 100 }
  validates :synopsis, presence: true, length: { minimum: 10 }
  validates :release_year, presence: true, numericality: { only_integer: true, greater_than: 1800, less_than_or_equal_to: Date.current.year }
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :director, presence: true, length: { minimum: 2, maximum: 75 }

  has_many :film_categories, dependent: :destroy
  has_many :categories, through: :film_categories

  has_many :film_tags, dependent: :destroy
  has_many :tags, through: :film_tags

  has_one_attached :poster

  def tag_list
    tags.pluck(:name).join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",")
                           .collect { |s| s.strip.downcase }
                           .uniq

    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }

    self.tags = new_or_found_tags
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
  before_action :authenticate_user!, except: [ :index, :show ]
  before_action :set_public_film, only: %i[show]
  before_action :set_secure_film, only: %i[edit update destroy]

  # GET /films
  def index
    @scope = Film.order(created_at: :desc)

    @scope = @scope.where("title ILIKE ?", "%#{params[:search_title]}%") if params[:search_title].present?
    @scope = @scope.where("director ILIKE ?", "%#{params[:search_director]}%") if params[:search_director].present?
    @scope = @scope.where(release_year: params[:search_year].to_i) if params[:search_year].present?

    if params[:search_category].present?
      @scope = @scope.joins(:film_categories)
                     .where(film_categories: { category_id: params[:search_category].to_i })
    end

    if params[:search_tags].present?
      tag_names = params[:search_tags].split(",").map(&:strip).map(&:downcase)
      @scope = @scope.joins(:tags).where("LOWER(tags.name) IN (?)", tag_names).distinct
    end

    @films = @scope.page(params[:page]).per(6)
  end

  # GET /films/1
  def show
    @comments = @film.comments.order(created_at: :desc)
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit; end

  # POST /films
  def create
    @film = current_user.films.build(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: "Filme criado com sucesso." }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: "Filme atualizado com sucesso.", status: :see_other }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  def destroy
    @film.destroy!
    respond_to do |format|
      format.html { redirect_to films_path, notice: "Filme apagado com sucesso.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private

  def set_public_film
    @film = Film.find(params[:id])
  end

  def set_secure_film
    @film = current_user.films.find(params[:id])
  end

  def film_params
    params.require(:film).permit(:title, :synopsis, :release_year, :duration, :director, :poster, :tag_list, category_ids: [])
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/_film.html.erb
<div class="film-card <%= "full-show" if local_assigns[:full_show] %>" id="<%= dom_id film %>" data-fade-in-target="item">

  <% if film.poster.attached? %>
    <div class="film-poster-container">
      <%= image_tag film.poster, class: "film-poster-image" %>
    </div>
  <% end %>

  <div class="film-info">
    <p><strong><%= t('activerecord.attributes.film.title') %>:</strong> <%= film.title %></p>
    <p><strong><%= t('activerecord.attributes.film.synopsis') %>:</strong> <%= truncate(film.synopsis, length: 120) %></p>
    <p><strong><%= t('activerecord.attributes.film.release_year') %>:</strong> <%= film.release_year %></p>
    <p><strong><%= t('activerecord.attributes.film.duration') %>:</strong> <%= film.duration %> min</p>
    <p><strong><%= t('activerecord.attributes.film.director') %>:</strong> <%= film.director %></p>

    <% if film.categories.any? %>
      <p>
        <strong><%= t('activerecord.attributes.film.category_ids') %>:</strong>
        <% film.categories.each do |category| %>
          <span class="film-category-badge"><%= category.name %></span>
        <% end %>
      </p>
    <% end %>

    <% if film.tags.any? %>
      <p>
        <strong><%= t('activerecord.attributes.film.tag_list') %>:</strong>
        <% film.tags.each do |tag| %>
          <span class="film-tag-badge" data-controller="highlight" data-highlight-tag-value="<%= tag.name %>"><%= tag.name %></span>
        <% end %>
      </p>
    <% end %>
  </div>

  <% unless local_assigns[:full_show] %>
    <div class="film-show-link-container">
      <%= link_to t('common.show'), film, class: "btn btn-sm btn-outline-primary" %>
    </div>
  <% end %>
</div>

app/views/films/_form.html.erb
<%= form_with(model: film, local: true) do |form| %>
  <% if film.errors.any? %>
    <div style="color: red">
      <h2>
        <%= pluralize(film.errors.count, t('errors.prohibited', default: "erro")) %>
        <%= t('errors.prohibited_from_saving', default: "proibiu que este filme fosse salvo") %>:
      </h2>

      <ul>
        <% film.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :synopsis %>
    <%= form.text_area :synopsis %>
  </div>

  <div>
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>

  <div>
    <%= form.label :duration %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :director %>
    <%= form.text_field :director %>
  </div>

  <div>
    <%= form.label :poster %><br>
    <%= form.file_field :poster %>
  </div>

  <h3><%= t('activerecord.models.category.other', default: "Categorias") %></h3>
  <% Category.all.each do |category| %>
    <%= form.check_box :category_ids, { multiple: true }, category.id, nil %>
    <%= form.label "category_#{category.id}", category.name %>
    <br>
  <% end %>

  <div>
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, value: @film.tags.pluck(:name).join(', '), style: "width: 400px;" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/films/edit.html.erb
<% content_for :title, "Editing film" %>

<h1><%= t('.title') %></h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to t('common.show'), @film %>
  <%= link_to t('common.back'), films_path %>
</div>

app/views/films/index.html.erb
<% content_for :title, t('.title') %>

<h1><%= t('.title') %></h1>

<%= form_with(url: films_path, method: :get, local: true) do |form| %>
  <div class="search-form-container">
    <div class="search-field">
      <%= form.label :search_title, t('.search_title') %><br>
      <%= form.text_field :search_title, value: params[:search_title], placeholder: t('.placeholder_title') %>
    </div>

    <div class="search-field">
      <%= form.label :search_director, t('.search_director') %><br>
      <%= form.text_field :search_director, value: params[:search_director], placeholder: t('.placeholder_director') %>
    </div>

    <div class="search-field">
      <%= form.label :search_year, t('.search_year') %><br>
      <%= form.number_field :search_year, value: params[:search_year], placeholder: t('.placeholder_year') %>
    </div>

    <div class="search-field">
      <%= form.label :search_category, t('activerecord.models.category.one', default: "Categoria") %><br>
      <%= form.select :search_category, options_from_collection_for_select(Category.all, :id, :name, params[:search_category]), include_blank: t('.all_categories') %>
    </div>

    <div class="search-field">
      <%= form.label :search_tags, t('.search_tags') %><br>
      <%= form.text_field :search_tags, value: params[:search_tags], placeholder: t('.placeholder_tags') %>
    </div>

    <div>
      <%= form.submit t('.search'), class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<% if user_signed_in? %>
  <div class="action-buttons-container">
    <%= link_to t('.new_film'), new_film_path, class: "btn btn-success" %>
    <%= link_to t('.import_films'), new_import_path, class: "btn btn-warning" %> 
    <%= link_to t('categories.index.new_category'), new_category_path, class: "btn btn-info" %>
  </div>
<% end %>

<% if @films.any? %>
  
  <div id="films" data-controller="fade-in">
    <% @films.each do |film| %>
      <%= render film %>
    <% end %>
  </div>
<% else %>
  <p><%= t('films.index.no_films_found', default: "Nenhum filme encontrado com os critérios de busca.") %></p>
<% end %>


<div class="pagination-container">
  <%= paginate @films %>
</div>

app/views/films/new.html.erb
<% content_for :title, "New film" %>

<h1><%= t('.title') %></h1>

<%= render "form", film: @film %>

<br>

<div>
  <%= link_to t('common.back'), films_path %>
</div>

app/views/films/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="film-card" id="<%= dom_id @film %>">
  <% if @film.poster.attached? %>
    <div class="film-poster-container">
      <%= image_tag @film.poster, class: "film-poster-image" %>
    </div>
  <% end %>

  <div class="film-info">
    <p><strong><%= t('activerecord.attributes.film.title') %>:</strong> <%= @film.title %></p>
    <p><strong><%= t('activerecord.attributes.film.synopsis') %>:</strong> <%= @film.synopsis %></p>
    <p><strong><%= t('activerecord.attributes.film.release_year') %>:</strong> <%= @film.release_year %></p>
    <p><strong><%= t('activerecord.attributes.film.duration') %>:</strong> <%= @film.duration %> min</p>
    <p><strong><%= t('activerecord.attributes.film.director') %>:</strong> <%= @film.director %></p>

    <% if @film.categories.any? %>
      <p>
        <strong><%= t('activerecord.attributes.film.category_ids') %>:</strong>
        <% @film.categories.each do |category| %>
          <span class="film-category-badge"><%= category.name %></span>
        <% end %>
      </p>
    <% end %>

    <% if @film.tags.any? %>
      <p>
        <strong><%= t('activerecord.attributes.film.tag_list') %>:</strong>
        <% @film.tags.each do |tag| %>
          <span class="film-tag-badge"><%= tag.name %></span>
        <% end %>
      </p>
    <% end %>
  </div>
</div>

<div class="film-actions" style="margin-top: 20px;">
  <% if @film.user == current_user %>
    <%= link_to t('common.edit'), edit_film_path(@film), class: "btn btn-primary" %>
    <%= button_to t('common.destroy'), @film, method: :delete, data: { confirm: t('common.confirm_destroy') }, class: "btn btn-danger" %>
  <% end %>

  <%= link_to t('common.back'), films_path, class: "btn btn-info" %>
</div>

<hr>

<h3><%= t('films.show.comments_title') %> (<%= @film.comments.count %>)</h3>

<div id="comments">
  <% if @film.comments.any? %>
    <% @film.comments.each do |comment| %>
      <div class="comment-card">
        <p>
          <strong><%= comment.author_name %></strong>
          <span style="color: #888; font-size: 0.8em;">
            comentou em <%= l(comment.created_at, format: :short) %>
          </span>
        </p>
        <p><%= comment.content %></p>
      </div>
    <% end %>
  <% else %>
    <p><%= t('films.show.be_first_comment') %></p>
  <% end %>
</div>

<hr>

<h3><%= t('films.show.add_comment') %></h3>

<%= form_with(model: [@film, @film.comments.build], local: true) do |form| %>
  <% unless user_signed_in? %>
    <p>
      <%= form.label :author_name, t('films.show.your_name') %><br>
      <%= form.text_field :author_name %>
    </p>
  <% end %>

  <p>
    <%= form.label :content, t('films.show.comment_label') %><br>
    <%= form.text_area :content, rows: 5 %>
  </p>

  <p>
    <%= form.submit t('films.show.submit_comment'), class: "btn btn-primary" %>
  </p>
<% end %>