config/routes.rb
Rails.application.routes.draw do
  resources :imports, only: [ :new, :create, :show ]

  resources :categories
  root "films#index"

  resources :films do
    resources :comments, only: [ :create ]
  end

  devise_for :users

  require "sidekiq/web"
  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :film_categories, dependent: :destroy
    has_many :films, through: :film_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save

        format.html { redirect_to @category, notice: t(".notice") }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)

        format.html { redirect_to @category, notice: t(".notice"), status: :see_other }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, notice: t(".notice"), status: :see_other }
      format.json { head :no_content }
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong><%= Category.human_attribute_name(:name) %>:</strong>
    <%= category.name %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div class="alert alert-danger"> 
      <h2>
        <%= pluralize(category.errors.count, t('errors.prohibited', default: "erro")) %>
        <%= t('errors.prohibited_from_saving', default: "proibiu que esta categoria fosse salva") %>:
      </h2>
      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, t('.title') %>

<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to t('common.show'), @category %> |
  <%= link_to t('categories.index.title'), categories_path %> 
</div>

app/views/categories/index.html.erb
<% content_for :title, t('.title') %>

<h1><%= t('.title') %></h1>

<div id="categories">
  <% @categories.each do |category| %>
    <%= render category %> 
    <p>
      <%= link_to t('common.show'), category %> | 
      <%= link_to t('common.edit'), edit_category_path(category) %> | 
      <%= button_to t('common.destroy'), category, method: :delete, data: { confirm: t('common.confirm_destroy') }, form: { style: 'display:inline-block;' } %>
    </p>
    <hr>
  <% end %>
</div>

<%= link_to t('.new_category'), new_category_path %>

app/views/categories/new.html.erb
<% content_for :title, t('.title') %>

<h1><%= t('.title') %></h1>

<%= render "form", category: @category %>

<br>

<%# Link "Voltar" estilizado como botão secundário com margem acima %>
<div>
  <%= link_to t('categories.index.title'), categories_path, class: "btn btn-secondary mt-3" %>
</div>

app/views/categories/show.html.erb
<% content_for :title, @category.name %> 

<%= render @category %> 

<hr> 

<div>
  <%= link_to t('.edit'), edit_category_path(@category) %> |
  <%= link_to t('.back'), categories_path %> |
  <%= button_to t('.destroy'), @category, method: :delete, data: { confirm: t('common.confirm_destroy') }, form: { style: 'display:inline-block;' } %>
</div>